---
title: "輸入與輸出作業"
author: "高紫芸"
date: "2018/11/11"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# read.csv() 使⽤預設參數
csv_url <- "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.csv"
csv_df <- read.csv(csv_url)
View(csv_df)
# read.csv() ⾃⾏指定變數的名稱
csv_url <- "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.csv"
csv_df <- read.csv(csv_url, skip = 1, header = FALSE, col.names = c('number', 'player', 'pos', 'ht', 'wt', 'birth_date', 'college'))
View(csv_df)
```

```{r}
# read.table() 指定 sep = ";"
txt_url <- "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.txt"
txt_df <- read.table(txt_url, sep = ";", header = TRUE)
View(txt_df)
```

```{r}
file_path <- "/Users/username/favorite_bands.txt"
favorite_bands <- read.table(file_path, header = TRUE, stringsAsFactors = FALSE)
View(favorite_bands)
```

```{r}
file_path <- "/Users/username/favorite_bands.csv"
favorite_bands <- read.table(file_path, header = TRUE, stringsAsFactors = FALSE, sep = ",")
View(favorite_bands)
```

```{r}
url <- "https://storage.googleapis.com/learn-r-the-easy-way.appspot.com/data_ch11/favorite_bands.csv"
favorite_bands <- read.table(url, header = TRUE, stringsAsFactors = FALSE, sep = ",")
View(favorite_bands)
```

```{r}
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
wine_quality_red <- read.table(url, header = TRUE, sep = ":")
View(wine_quality_red)
```

```{r}
favorite_bands_df <- data.frame(band = c("Beyond", "Beatles"), lead_vocal = c("Wong Ka Kui", "John Lennon"), formed = c(1983, 1960))
file_path <- "/Users/username/favorite_bands.txt"
write.table(favorite_bands_df, file = file_path, row.names = FALSE)
```

```{r}
favorite_bands_df <- data.frame(band = c("Beyond", "Beatles"), lead_vocal = c("Wong Ka Kui", "John Lennon"), formed = c(1983, 1960))
file_path <- "/Users/username/favorite_bands.csv"
write.table(favorite_bands_df, file = file_path, row.names = FALSE, sep = ",")
```

```{r}
# readxl::read_excel() 函數使⽤預設參數
if (!require(readxl)) {
 install.packages("readxl")
 library(readxl)
}
xlsx_url <- "https://storage.googleapis.com/ds_data_import/fav_nba_teams.xlsx"
dest_file <- "~/Desktop/fav_nab_teams.xlsx"
download.file(xlsx_url, destfile = dest_file)
chicago_bulls <- read_excel(dest_file)
View(chicago_bulls)
# readxl::read_excel() 函數指定⼯作表與讀取範圍
if (!require(readxl)) {
 install.packages("readxl")
 library(readxl)
}
xlsx_url <- "https://storage.googleapis.com/ds_data_import/fav_nba_teams.xlsx"
dest_file <- "~/Desktop/fav_nab_teams.xlsx"
download.file(xlsx_url, destfile = dest_file)
boston_celtics <- read_excel(dest_file, sheet = "boston_celtics_2007_2008", range = "A7:C16", col_names = c("number", "player", "pos"))
View(boston_celtics)
```

```{r}
# jsonlite::fromJSON() 函數載入 JSON 檔案
if (!require(jsonlite)) {
 install.packages("jsonlite")
 library(jsonlite)
}
json_url <- "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.json"
chicago_bulls_list <- fromJSON(json_url)
chicago_bulls_list
# 計算勝率或者從先發陣容中選出最喜歡的球員
winning_rate <- chicago_bulls_list$records$wins / (chicago_bulls_list$records$wins + chicago_bulls_list$records$losses)
fav_player <- chicago_bulls_list$starting_lineups$SG
sprintf("勝率為 %.2f", winning_rate)
sprintf("最喜歡的球員是 %s", fav_player)
```

```{r}
# 安裝與載入套件
install.packages("readxl") # 如果先前已經安裝過就不⽤執⾏這⾏
library(readxl)`
# 讀入
file_path <- "/Users/username/favorite_bands.xlsx"
favorite_bands <- read_excel(file_path)
```

```{r}
# 安裝與載入套件
install.packages("jsonlite") # 如果先前已經安裝過就不⽤執⾏這⾏
library(jsonlite)
# 讀入
file_path <- "/Users/username/favorite_bands.json"
favorite_bands <- fromJSON(file_path)
View(favorite_bands)
# 輸出
favorite_bands_df <- data.frame(band = c("Beyond", "Beatles"), lead_vocal = c("Wong Ka Kui", "John Lennon"), formed = c(1983, 1960))
toJSON(favorite_bands_df)
```


